services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
      - "3001:3001"
    volumes:
      - hl-data:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - hl-data:/home/hluser/hl/data

  trade-redis-project:
    restart: unless-stopped
    build: ./trade-redis-project  
    ports:
      - "3000:3000"
    volumes:
      - hl-data:/home/hluser/hl/data
    environment:
      - REDIS_URL=tcp://6.tcp.ngrok.io:15139  # Replace with your ngrok tunnel URL when deploying in the cloud
      - PROD=true

volumes:
  hl-data:
    driver: local
